on: [push]

jobs:
  build:
    runs-on: 'ubuntu-22.04'

    steps:
    - name: 'Git checkout'
      uses: actions/checkout@v3

    - name: 'Install dosbox-x (apt)'
      run: sudo snap install dosbox-x

    - name: 'Make build dir'
      run: |
        mkdir build

    - name: 'Setup node'
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: 'Prepare Assets'
      run: |
        node scripts/generateAssetsBatch.js assets build/assets.bat
        cat build/assets.bat

    - name: 'Compile'
      uses: 'joncloud/dos-build-action@main'
      timeout-minutes: 2
      with:
        programs: |
          $/turbo-asm/2.01:c:\tasm
          $/turbo-c++/3.00:c:\tc
          src:c:\src
          build:c:\build
        run: |
          c:
          cd \src\digisnd
          make > c:\build\digisnd.txt
          cd \src\utility
          make > c:\build\utility.txt
          cd \src\_g1
          make > c:\build\_g1.txt
          cd \src\_g2
          make > c:\build\_g2.txt
          cd \src\_g3
          make > c:\build\_g3.txt
          SET PATH=c:\src\utility;%PATH%
          cd \
          c:\build\assets.bat

        conf: |
          [dosbox]
          memsize=256

          [cpu]
          cycles=max
          turbo=true

    - name: 'Prepare Results'
      if: always()
      run: |
        echo "DIGISND"
        cat build/DIGISND.TXT
        echo "UTILITY"
        cat build/UTILITY.TXT
        echo "_G1"
        cat build/_G1.TXT
        echo "_G2"
        cat build/_G2.TXT
        echo "_G3"
        cat build/_G3.TXT
        echo "ASSETS"
        cat build/ASSETS.TXT

        rm build/DIGISND.TXT
        rm build/UTILITY.TXT
        rm build/_G1.TXT
        rm build/_G2.TXT
        rm build/_G3.TXT
        rm build/ASSETS.TXT

        rm build/assets.bat

        cp src/_g1/_G1.EXE build/
        cp src/_g2/_G2.EXE build/
        cp src/_g3/_G3.EXE build/
        cp src/utility/LVLBUILD.EXE build/
        cp src/utility/MAPGEN.EXE build/
        cp src/utility/PCXRES.EXE build/
        cp src/utility/PCX_IMP.EXE build/
        cp src/utility/RES.EXE build/
        cp src/utility/SPRITEED.EXE build/
        cp src/utility/TH.EXE build/
        cp src/utility/XP_IMP.EXE build/
        cp src/utility/XSPRITE.EXE build/

    - uses: 'actions/upload-artifact@v3'
      with:
        name: 'build'
        path: build
